language: node_js

node_js:
  - "6.10.0"

cache:
  directories:
    - ~/ .npm
    - node_modules

install:
  - npm install
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - npm start -- --silent &

script:
  - node_modules/.bin/newman run tests/bitcoinz.postman_collection.json
  - ./node_modules/.bin/cypress run cypress/integration/galen_example.js
